site_name: AWS Deadline Cloud Integrations
site_description: Documentation for AWS Deadline Cloud integrations
site_url: https://aws-deadline.github.io
theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
    accent: orange
  custom_dir: overrides
  font: false
  logo: assets/images/logo.png
  favicon: assets/images/logo.png
extra_css:
- stylesheets/extra.css
plugins:
- search
- gen-files:
    scripts:
    - gen_files/generate_content.py
markdown_extensions:
- admonition
- codehilite
- toc:
    toc_depth: 1-1
use_directory_urls: true
nav:
- Home: index.md
- Adobe After Effects:
  - Overview: after-effects/index.md
  - Releases: after-effects/releases.md
- Autodesk 3ds Max:
  - Overview: 3ds-max/index.md
  - Releases: 3ds-max/releases.md
- Autodesk Maya:
  - Overview: maya/index.md
  - Releases: maya/releases.md
- Blender:
  - Overview: blender/index.md
  - Releases: blender/releases.md
- Foundry Nuke:
  - Overview: nuke/index.md
  - Releases: nuke/releases.md
- KeyShot Studio:
  - Overview: keyshot/index.md
  - User Guide: keyshot/user-guide.md
  - Releases: keyshot/releases.md
- Maxon Cinema 4D:
  - Overview: cinema-4d/index.md
  - User Guide: cinema-4d/user-guide.md
  - Releases: cinema-4d/releases.md
- SideFX Houdini:
  - Overview: houdini/index.md
  - Releases: houdini/releases.md
- Unreal Engine:
  - Overview: unreal-engine/index.md
  - Releases: unreal-engine/releases.md
extra:
  generator: false
