on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      oses:
        required: true
        type: string
      project_name:
        required: true
        type: string

jobs:
  ReleaseInstaller:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    strategy:
      matrix:
        os: ${{ fromJson(inputs.oses) }}    
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_CODEBUILD_MAINLINE_INSTALLER_ROLE }}
          aws-region: us-west-2
          mask-aws-account-id: true
      - name: Run CodeBuild
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: ReleaseInstallerProject
          hide-cloudwatch-logs: true
          env-vars-for-codebuild: |
              REPONAME,
              OPERATING_SYSTEM,
              VERSION
        env:
          REPONAME: ${{ inputs.project_name }}
          OPERATING_SYSTEM: ${{ matrix.os }}
          VERSION: ${{ inputs.tag }}