name: "Prerelease"

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string


jobs:
  PreRelease:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: refs/tags/${{inputs.tag}}
          fetch-depth: 0
          token: ${{ secrets.CI_TOKEN }}

      - name: Build
        run: |
          pip install --upgrade hatch click==8.2
          hatch -v build

      # A precommit hook into the GitHub Action workflow.
      # If the workflow file .github/actions/prepush_release_hook exists in the repository
      # that is using this workflow, then this will run the workflow defined in that file.
      # That workflow must be defined to accept all of the inputs in the 'with' clause below.
      # Uses:
      #  If a package publish needs to publish additional files to the GitHub release, then
      #  it should use this hook to:
      #    1. create a dist_extras/ directory
      #    2. add all additional files to publish into that directory that aren't publishable to PyPI
      - name: PrePushReleaseHook
        uses: ./.github/actions/prepush_release_hook
        if: ${{ hashFiles('./.github/actions/prepush_release_hook/action.yml') != '' }}
        with:
          semver: ${{ inputs.tag }}
          tag: ${{ inputs.tag }}

      - name: UploadArtifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: |
            dist
            dist_extras